import { useState, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useChatStore } from '@/stores/chat'

interface SearchDialogProps {
  onClose: () => void
}

const suggestedPrompts = [
  '如何快速上手Vue3框架',
  '入职字节跳动难吗？',
  '前端如何实现弹性布局',
  '喝酒脸红是会喝酒的表现吗？',
  'React Hooks 的使用技巧',
  'TypeScript 高级类型有哪些',
  '如何优化前端性能',
  'JavaScript 闭包的原理',
  'CSS Grid 布局教程',
  'Webpack 配置优化',
  'Node.js 异步编程',
  'MongoDB 数据库设计',
  'Redis 缓存使用场景',
  'Docker 容器化部署',
  'Linux 常用命令',
  'Git 版本控制最佳实践',
  'RESTful API 设计规范',
  'GraphQL 与 REST 的区别',
  'WebSocket 实时通信',
  'JWT 身份认证',
  'OAuth2.0 授权流程',
  'HTTPS 加密原理',
  'TCP/IP 协议详解',
  'HTTP/2 与 HTTP/3',
  'CDN 内容分发网络',
  '负载均衡算法',
  '微服务架构设计',
  '分布式系统一致性',
  '消息队列使用场景',
  'Kafka 消息中间件',
  'RabbitMQ 队列管理',
  'Elasticsearch 搜索引擎',
  'Logstash 日志收集',
  'Kibana 数据可视化',
  'Prometheus 监控系统',
  'Grafana 仪表盘',
  'Jenkins CI/CD 流程',
  'GitHub Actions 自动化',
  'Docker Compose 编排',
  'Kubernetes 容器编排',
  'Helm 包管理',
  'Istio 服务网格',
  'Consul 服务发现',
  'Nginx 反向代理',
  'Apache 服务器配置',
  'Tomcat 应用服务器',
  'Spring Boot 快速入门',
  'Spring Cloud 微服务',
  'MyBatis ORM 框架',
  'Hibernate JPA 规范',
  'JPA 实体关系映射',
  'Maven 依赖管理',
  'Gradle 构建工具',
  'JUnit 单元测试',
  'Mockito 模拟测试',
  'Selenium 自动化测试',
  'JMeter 性能测试',
  'Python 数据分析',
  'Pandas 数据处理',
  'NumPy 科学计算',
  'Matplotlib 数据可视化',
  'Scikit-learn 机器学习',
  'TensorFlow 深度学习',
  'PyTorch 神经网络',
  'Keras 模型构建',
  'Flask Web 框架',
  'Django 全栈开发',
  'FastAPI 高性能 API',
  'Celery 异步任务',
  'Redis Python 客户端',
  'MongoDB Python 驱动',
  'PostgreSQL 数据库',
  'MySQL 优化技巧',
  'SQL 查询优化',
  '数据库索引原理',
  '事务隔离级别',
  '数据库设计范式',
  'E-R 图建模',
  '数据仓库架构',
  '数据挖掘算法',
  '大数据处理技术',
  'Hadoop 生态系统',
  'Spark 分布式计算',
  'Flink 流处理',
  'Hive 数据仓库',
  'HBase NoSQL',
  'Cassandra 分布式数据库',
  '区块链技术原理',
  '以太坊智能合约',
  'Solidity 编程语言',
  'Web3 开发入门',
  'DeFi 去中心化金融',
  'NFT 数字藏品',
  '加密货币交易',
  '比特币挖矿原理',
  '共识算法比较',
  '零知识证明',
  '跨链技术',
  'Layer2 扩容方案',
  '智能合约安全',
  '算法复杂度分析',
  '数据结构基础',
  '排序算法实现',
  '查找算法优化',
  '动态规划解题',
  '贪心算法应用',
  '回溯算法模板',
  '图算法遍历',
  '最短路径算法',
  '最小生成树',
  '网络流算法',
  '字符串匹配算法',
  '位运算技巧',
  '递归与迭代',
  '分治算法思想',
  '设计模式应用',
  '单例模式实现',
  '工厂模式使用',
  '观察者模式',
  '策略模式选择',
  '适配器模式转换',
  '装饰器模式增强',
  '代理模式控制',
  '组合模式结构',
  '命令模式封装',
  '责任链模式',
  '状态机设计',
  '模板方法模式',
  '迭代器模式',
  '访问者模式',
  '备忘录模式',
  '解释器模式',
  '架构设计原则',
  'SOLID 原则',
  'DRY 原则',
  'KISS 原则',
  'YAGNI 原则',
  '代码重构技巧',
  '代码审查清单',
  '单元测试覆盖率',
  '集成测试策略',
  '端到端测试',
  '测试驱动开发',
  '行为驱动开发',
  '敏捷开发实践',
  'Scrum 框架',
  'Kanban 看板',
  'DevOps 文化',
  '持续集成部署',
  '基础设施即代码',
  '监控告警系统',
  '日志分析工具',
  '性能调优方法',
  '内存泄漏排查',
  'CPU 优化技巧',
  'I/O 性能提升',
  '网络延迟优化',
  '并发编程模型',
  '多线程同步',
  '锁机制实现',
  '无锁编程',
  '协程异步编程',
  '响应式编程',
  '函数式编程',
  '面向对象设计',
  '领域驱动设计',
  '事件驱动架构',
  'CQRS 模式',
  '事件溯源',
  '六边形架构',
  '洋葱架构',
  '整洁架构',
  '微前端架构',
  'Serverless 架构',
  '云原生技术',
  '容器编排调度',
  '服务网格治理',
  '混沌工程实践',
  '故障排查方法',
  '系统监控指标',
  'APM 性能监控',
  '日志聚合分析',
  '链路追踪技术',
  '分布式追踪',
  '服务降级策略',
  '熔断器模式',
  '限流算法实现',
  '缓存穿透击穿',
  '分布式锁实现',
  '分布式事务处理',
  'CAP 定理应用',
  'BASE 理论',
  '最终一致性',
  '幂等性设计',
  '接口幂等实现',
  '重试机制设计',
  '超时控制策略',
  '心跳检测机制',
  '健康检查接口',
  '优雅停机方案',
  '灰度发布策略',
  '蓝绿部署',
  '金丝雀发布',
  'A/B 测试',
  '用户行为分析',
  '数据埋点方案',
  '推荐系统算法',
  '搜索相关性优化',
  '自然语言处理',
  '计算机视觉应用',
  '语音识别技术',
  '机器学习模型',
  '深度学习框架',
  '强化学习入门',
  'GAN 生成对抗网络',
  'RNN 循环神经网络',
  'CNN 卷积神经网络',
  'Transformer 模型',
  'BERT 预训练模型',
  'GPT 大语言模型',
  'LLM 应用开发',
  'Prompt 工程技巧',
  'RAG 检索增强生成',
  '向量数据库应用',
  'Embedding 向量化',
  '知识图谱构建',
  '图神经网络',
  '联邦学习隐私',
  '模型压缩技术',
  '模型量化优化',
  '边缘计算部署',
  'AI 模型服务化',
  '模型监控管理',
  '数据标注工具',
  '特征工程方法',
  '特征选择技巧',
  '数据清洗流程',
  '异常检测算法',
  '时间序列分析',
  '预测模型构建',
  '分类算法比较',
  '回归模型选择',
  '聚类算法应用',
  '降维技术实现',
  '集成学习方法',
  'Boosting 算法',
  'Bagging 集成',
  'Stacking 模型融合',
  '交叉验证技巧',
  '超参数调优',
  '网格搜索优化',
  '贝叶斯优化',
  '早停策略',
  '学习率调度',
  '正则化技术',
  'Dropout 正则化',
  'Batch Normalization',
  '激活函数选择',
  '损失函数设计',
  '优化器比较',
  '梯度下降变种',
  '动量优化算法',
  '自适应学习率',
  '梯度裁剪技巧',
  '权重初始化方法',
  'Xavier 初始化',
  'He 初始化',
  '迁移学习应用',
  '预训练模型微调',
  '少样本学习',
  '零样本学习',
  '自监督学习',
  '对比学习',
  '多任务学习',
  '元学习入门',
  '终身学习',
  '持续学习',
  '增量学习算法',
  '在线学习系统',
  '强化学习环境',
  'Q-Learning 算法',
  '策略梯度方法',
  'Actor-Critic 架构',
  'PPO 近端策略优化',
  'DDPG 深度确定性策略',
  'A3C 异步优势演员评论家',
  'AlphaGo 原理',
  '蒙特卡洛树搜索',
  '博弈论基础',
  '纳什均衡',
  '拍卖机制设计',
  '激励机制设计',
  '算法交易策略',
  '量化投资入门',
  '技术分析指标',
  '基本面分析',
  '风险管理模型',
  'VaR 风险价值',
  '期权定价模型',
  '布莱克-舒尔斯公式',
  '投资组合优化',
  '马科维茨理论',
  '资本资产定价',
  '有效市场假说',
  '行为金融学',
  '金融科技应用',
  '数字货币监管',
  '支付系统设计',
  '风控系统架构',
  '反欺诈检测',
  '信用评分模型',
  '贷款审批流程',
  '保险精算基础',
  '再保险原理',
  '精算数学方法',
  '寿险精算',
  '非寿险精算',
  '资产负债管理',
  '利率风险管理',
  '外汇风险管理',
  '商品期货交易',
  '股指期货策略',
  '期权组合策略',
  '波动率交易',
  '套利交易机会',
  '统计套利',
  '配对交易策略',
  '均值回归策略',
  '动量交易策略',
  '反转交易策略',
  '事件驱动策略',
  '并购套利',
  '困境资产投资',
  '私募股权投资',
  '风险投资逻辑',
  '天使投资评估',
  '创业融资技巧',
  '商业计划书',
  '估值方法比较',
  'DCF 估值模型',
  '相对估值法',
  '可比公司分析',
  '先例交易分析',
  '杠杆收购',
  '管理层收购',
  'IPO 流程',
  '股票上市要求',
  '退市机制',
  '股票拆分',
  '股利政策',
  '股票回购',
  '公司治理结构',
  '董事会职责',
  '股东大会',
  '独立董事制度',
  '内部控制制度',
  '审计委员会',
  '薪酬委员会',
  '提名委员会',
  '企业社会责任',
  'ESG 投资',
  '可持续发展',
  '碳中和目标',
  '绿色金融产品',
  '绿色债券发行',
  '碳交易市场',
  '碳信用机制',
  '清洁能源投资',
  '新能源技术',
  '太阳能发电',
  '风力发电',
  '储能技术',
  '电动汽车',
  '充电桩建设',
  '智能电网',
  '电力市场改革',
  '能源互联网',
  '综合能源服务',
  '能源大数据',
  '能源区块链',
  '能源数字化转型',
  '工业4.0',
  '智能制造',
  '工业互联网',
  '数字孪生',
  '边缘计算应用',
  '5G 通信技术',
  '6G 研究进展',
  '物联网架构',
  '传感器网络',
  'RFID 技术',
  'NB-IoT 窄带物联网',
  'LoRa 远距离通信',
  'ZigBee 无线通信',
  '蓝牙技术',
  'WiFi 6 标准',
  'WiFi 7 发展',
  '卫星通信',
  '量子通信',
  '光通信技术',
  '光纤网络',
  '网络虚拟化',
  'SDN 软件定义网络',
  'NFV 网络功能虚拟化',
  '网络切片技术',
  'MEC 多接入边缘计算',
  '云网融合',
  '算力网络',
  '东数西算',
  '数据中心建设',
  '机房设计标准',
  '服务器虚拟化',
  '桌面虚拟化',
  '应用虚拟化',
  '存储虚拟化',
  '网络虚拟化',
  '安全虚拟化',
  '虚拟化管理平台',
  '云操作系统',
  '容器云平台',
  'Serverless 平台',
  '函数计算服务',
  '云原生数据库',
  '分布式存储',
  '对象存储',
  '块存储',
  '文件存储',
  '存储网关',
  '备份恢复方案',
  '灾难恢复计划',
  '业务连续性',
  '高可用架构',
  '容灾切换',
  '双活数据中心',
  '多活架构',
  '异地多活',
  '同城双活',
  '混合云架构',
  '私有云建设',
  '公有云选择',
  '多云管理',
  '云成本优化',
  '云安全最佳实践',
  '零信任架构',
  '身份认证管理',
  '访问控制策略',
  '权限管理系统',
  '单点登录 SSO',
  '多因素认证 MFA',
  '生物识别技术',
  '密码学基础',
  '对称加密算法',
  '非对称加密',
  '哈希函数',
  '数字签名',
  '数字证书',
  'PKI 公钥基础设施',
  'CA 认证机构',
  'SSL/TLS 协议',
  'VPN 虚拟专用网',
  '防火墙配置',
  '入侵检测系统',
  '入侵防御系统',
  'WAF Web应用防火墙',
  'DDoS 防护',
  '安全审计',
  '合规性检查',
  '等级保护',
  'ISO 27001',
  'GDPR 合规',
  '数据隐私保护',
  '个人信息保护',
  '数据脱敏技术',
  '数据加密存储',
  '传输加密',
  '端到端加密',
  '同态加密',
  '安全多方计算',
  '隐私计算',
  '联邦学习隐私',
  '差分隐私',
  '匿名化技术',
  '假名化处理',
  '数据最小化',
  '目的限制原则',
  '数据保留策略',
  '数据删除权',
  '数据可携带权',
  '数据访问权',
  '数据更正权',
  '被遗忘权',
  '算法透明度',
  '算法公平性',
  '算法问责制',
  'AI 伦理规范',
  'AI 治理框架',
  'AI 风险管理',
  'AI 安全防护',
  '对抗样本攻击',
  '模型鲁棒性',
  'AI 可解释性',
  'XAI 可解释AI',
  'LIME 局部可解释',
  'SHAP 值分析',
  '注意力可视化',
  '特征重要性分析',
  '模型调试技巧',
  '错误分析',
  '偏差检测',
  '公平性评估',
  '包容性设计',
  '无障碍访问',
  '用户体验设计',
  'UI 设计原则',
  '交互设计模式',
  '视觉设计规范',
  '设计系统构建',
  '组件库开发',
  '设计令牌',
  '响应式设计',
  '移动端适配',
  'PWA 渐进式Web应用',
  '小程序开发',
  '跨平台开发',
  'React Native',
  'Flutter 开发',
  'Ionic 框架',
  'Electron 桌面应用',
  'Tauri 轻量级桌面',
  'WebAssembly 技术',
  'Rust 前端应用',
  'Go 语言开发',
  'C++ 前端优化',
  'WebGL 图形渲染',
  'Three.js 3D开发',
  'Babylon.js 引擎',
  'A-Frame VR开发',
  'WebXR 标准',
  'AR 增强现实',
  'VR 虚拟现实',
  'MR 混合现实',
  '元宇宙概念',
  '数字人技术',
  '虚拟主播',
  'AI 换脸技术',
  'Deepfake 检测',
  '内容审核',
  '文本分类',
  '情感分析',
  '命名实体识别',
  '关系抽取',
  '事件抽取',
  '知识抽取',
  '信息抽取',
  '文本摘要',
  '机器翻译',
  '问答系统',
  '对话系统',
  '聊天机器人',
  '智能客服',
  '语音助手',
  '语音识别',
  '语音合成',
  '声纹识别',
  '说话人识别',
  '语音情感识别',
  '语音增强',
  '语音降噪',
  '图像识别',
  '目标检测',
  '图像分割',
  '图像分类',
  '人脸识别',
  '人体姿态估计',
  '手势识别',
  '动作识别',
  '视频分析',
  '视频理解',
  '视频分类',
  '视频摘要',
  '视频检索',
  '视频压缩',
  '视频编码',
  '图像生成',
  '风格迁移',
  '图像修复',
  '超分辨率重建',
  '图像增强',
  '图像去噪',
  '图像去模糊',
  '图像去雨',
  '图像去雾',
  'OCR 文字识别',
  '文档分析',
  '表格识别',
  '票据识别',
  '身份证识别',
  '车牌识别',
  '二维码识别',
  '条形码识别',
  '医学影像分析',
  'CT 影像诊断',
  'MRI 影像分析',
  'X 光片诊断',
  '病理图像分析',
  '眼底图像分析',
  '皮肤病变识别',
  '癌症筛查',
  '疾病预测',
  '药物发现',
  '蛋白质结构预测',
  '基因测序分析',
  '生物信息学',
  '计算生物学',
  '系统生物学',
  '合成生物学',
  '基因编辑',
  'CRISPR 技术',
  '基因治疗',
  '细胞治疗',
  '免疫治疗',
  '精准医疗',
  '个性化医疗',
  '远程医疗',
  '互联网医疗',
  '智慧医院',
  '医疗信息化',
  '电子病历',
  'HIS 医院信息系统',
  'LIS 实验室信息系统',
  'PACS 影像归档系统',
  'EMR 电子病历系统',
  'PHR 个人健康档案',
  '健康大数据',
  '可穿戴设备',
  '健康监测',
  '运动追踪',
  '睡眠监测',
  '心率监测',
  '血压监测',
  '血糖监测',
  '血氧监测',
  '智能手环',
  '智能手表',
  '智能眼镜',
  '智能耳机',
  '智能家居',
  '智能音箱',
  '智能门锁',
  '智能摄像头',
  '智能照明',
  '智能窗帘',
  '智能空调',
  '智能冰箱',
  '智能洗衣机',
  '智能扫地机',
  '智能厨电',
  '全屋智能',
  '智慧社区',
  '智慧城市',
  '智慧交通',
  '智慧物流',
  '智慧零售',
  '智慧教育',
  '智慧旅游',
  '智慧政务',
  '智慧金融',
  '智慧医疗',
  '智慧农业',
  '智慧能源',
  '智慧环保',
  '智慧安防',
  '智慧园区',
  '智慧工厂',
  '智慧矿山',
  '智慧港口',
  '智慧机场',
  '智慧车站',
  '智慧地铁',
  '智慧公交',
  '智慧停车',
  '智慧充电',
  '智慧水务',
  '智慧燃气',
  '智慧热力',
  '智慧电网',
  '智慧建筑',
  '智慧办公',
  '智慧酒店',
  '智慧餐厅',
  '智慧商场',
  '智慧景区',
  '智慧博物馆',
  '智慧图书馆',
  '智慧体育馆',
  '智慧会展',
  '智慧媒体',
  '智慧广告',
  '智慧营销',
  '智慧客服',
  '智慧销售',
  '智慧采购',
  '智慧供应链',
  '智慧仓储',
  '智慧配送',
  '智慧售后',
  '智慧财务',
  '智慧人事',
  '智慧行政',
  '智慧法务',
  '智慧审计',
  '智慧风控',
  '智慧合规',
  '智慧战略',
  '智慧决策',
  '智慧管理',
  '智慧领导',
  '智慧组织',
  '智慧文化',
  '智慧品牌',
  '智慧创新',
  '智慧研发',
  '智慧设计',
  '智慧制造',
  '智慧质量',
  '智慧服务',
  '智慧运营',
  '智慧增长',
  '智慧转型',
  '数字化升级',
  '数字化转型',
  '数字化战略',
  '数字化组织',
  '数字化人才',
  '数字化文化',
  '数字化领导力',
  '数字化思维',
  '数字化能力',
  '数字化素养',
  '数字化技能',
  '数字化工具',
  '数字化平台',
  '数字化生态',
  '数字化治理',
  '数字化合规',
  '数字化安全',
  '数字化风险',
  '数字化投资',
  '数字化回报',
  '数字化价值',
  '数字化效益',
  '数字化效率',
  '数字化体验',
  '数字化创新',
  '数字化变革',
  '数字化颠覆',
  '数字化机遇',
  '数字化挑战',
  '数字化趋势',
  '数字化未来',
]

function SearchDialog({ onClose }: SearchDialogProps) {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedIndex, setSelectedIndex] = useState(-1)
  const inputRef = useRef<HTMLInputElement>(null)
  const navigate = useNavigate()
  const chatStore = useChatStore()

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.focus()
    }
  }, [])

  const filteredPrompts = suggestedPrompts.filter((prompt) =>
    prompt.toLowerCase().includes(searchQuery.toLowerCase())
  )

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value)
    setSelectedIndex(-1)
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setSelectedIndex((prev) =>
        prev < filteredPrompts.length - 1 ? prev + 1 : prev
      )
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setSelectedIndex((prev) => (prev > 0 ? prev - 1 : -1))
    } else if (e.key === 'Enter') {
      e.preventDefault()
      if (selectedIndex >= 0 && selectedIndex < filteredPrompts.length) {
        handlePromptSelect(filteredPrompts[selectedIndex])
      } else if (searchQuery.trim()) {
        handlePromptSelect(searchQuery.trim())
      }
    } else if (e.key === 'Escape') {
      onClose()
    }
  }

  const handlePromptClick = (prompt: string, index: number) => {
    setSelectedIndex(index)
    handlePromptSelect(prompt)
  }

  const handlePromptSelect = (prompt: string) => {
    chatStore.createConversation()
    navigate('/chat')
    setTimeout(() => {
      window.postMessage({ type: 'SET_INPUT_VALUE', value: prompt }, '*')
    }, 100)
    onClose()
  }

  return (
    <div className="search-dialog">
      <div className="search-header">
        <div className="search-input">
          <input
            ref={inputRef}
            type="text"
            placeholder="搜索或输入问题..."
            value={searchQuery}
            onChange={handleSearchChange}
            onKeyDown={handleKeyDown}
            autoFocus
          />
          <button className="close-btn" onClick={onClose}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      </div>
      <div className="dialog-content">
        {searchQuery === '' ? (
          <>
            <div className="initial-message">Hi, 我是你的AI小助手，有什么问题都可以问我！</div>
            <div className="suggested-prompts">
              <div className="prompt-title">建议提示词</div>
              <div className="prompt-list">
                {suggestedPrompts.slice(0, 8).map((prompt, index) => (
                  <button
                    key={index}
                    className="prompt-item"
                    onClick={() => handlePromptClick(prompt, index)}
                  >
                    {prompt}
                  </button>
                ))}
              </div>
            </div>
          </>
        ) : filteredPrompts.length > 0 ? (
          <div className="search-results">
            <div className="result-count">找到 {filteredPrompts.length} 个结果</div>
            <div className="prompt-list">
              {filteredPrompts.map((prompt, index) => (
                <button
                  key={index}
                  className={`prompt-item ${selectedIndex === index ? 'selected' : ''}`}
                  onClick={() => handlePromptClick(prompt, index)}
                >
                  {prompt}
                </button>
              ))}
            </div>
          </div>
        ) : (
          <div className="no-results">
            <div className="no-results-icon">🔍</div>
            <div className="no-results-text">未找到相关结果</div>
            <div className="no-results-hint">试试其他关键词</div>
          </div>
        )}
      </div>
    </div>
  )
}

export default SearchDialog
